org: spink
app: nft-vision-api-1
service: nft-vision-api
package:
  individually: true

provider:
  name: aws
  runtime: python3.8
  region: eu-west-1
  stage: ${opt:stage, "dev"}

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: non-linux
    layer:
      name: nft-vision-api-layer
      description: My awesome app layer
      compatibleRuntimes:
        - python3.8

functions:
  app:
    package:
      patterns:
        - "src/*"
        - ".env"
        - "!requirements.txt"
        - "!package.json"
        - "!__pycache__/***"
        - "!package-lock.json"
        - "!.serverless/**"
        - "!virtualenv/**"
        - "!node_modules/**"
        - "!venv/**"
        - "!notebooks/**"
        - "!.ipynb_checkpoints/**"
        - "!celery/**"
        - "!redshift/**"
        - "!*.ipynb"
    handler: src.main.handler
    environment:
      STAGE: ${self:provider.stage}
    layers:
      - { Ref: PythonRequirementsLambdaLayer }
    events:
      - http:
          method: any
          path: /{proxy+}